name: Extension-ExcellentEconomy
version: ${version}
main: net.incomemc.extension.excellenteconomy
api-version: '1.21'
authors: [ MatuMaKa ]
description: ExcellentEconomy plugin DataExtension for Plan
depend:
  - Plan
  - ExcellentEconomy